name: outdoor_aerial_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

dependencies:
  drift: ^2.30.0
  drift_postgres: ^1.3.1
  logging: ^1.3.0
  postgres: ^3.5.9
  protobuf: ^6.0.0
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  shelf: ^1.4.2
  shelf_router: ^1.1.2
  shelf_web_socket: ^3.0.0

dev_dependencies:
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  drift_dev: ^2.30.0
  http: ^1.2.2
  lints: ^6.0.0
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  test: ^1.25.6
